version: '3.8'
services:
  async-backend:
    build:
      context: .
      target: development
    ports:
      - "9230:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
