version: '3.8'
services:
  async-backend:
    build: .
    image: async-backend
    container_name: async-backend
    environment:
      AZURE_SERVICE_BUS_HOST: ${AZURE_SERVICE_BUS_HOST}
      AZURE_SERVICE_BUS_USERNAME: ${AZURE_SERVICE_BUS_USERNAME}
      AZURE_SERVICE_BUS_PASSWORD: ${AZURE_SERVICE_BUS_PASSWORD}
      AZURE_SERVICE_BUS_QUEUE: ${AZURE_SERVICE_BUS_QUEUE}
      AZURE_SERVICE_BUS_SESSION_QUEUE: ${AZURE_SERVICE_BUS_SESSION_QUEUE}
